### ISSUE TITLE
Ad validates from URL, fails from .zip

### ISSUE THREAD

**Issue by fillefrans** [gardr/validator-web#56]
This creative validates when tested from URL: (http://kreateam.viewshq.no:8080/html5/gardrBug/) 

However, when I try to validate the zip-file (http://kreateam.viewshq.no:8080/html5/gardrBug.zip), the validation [fails](http://validator.gardr.org/result?id=1d36bbdb-4d31-425c-ba8b-3eb0d37e5a89-151422-000857)

**Comment by sveisvei** [comment]
@fillefrans Did not get to download the zip now, if possible can you reupload - or just run on validator and pass me the ID. (the last ID has timed out)
