### ISSUE TITLE
Possible to ignore scripts from certain CDNs?

### ISSUE THREAD

**Issue by wwalmnes** [gardr/validator-web#57]
When validating an ad, scripts such as jQuery (from http://cdn.vgc.no/js/libs/jquery/jquery-1.11.0.min.js) is added to the payload. However these scripts are used on the main site (e.g. VG.no), which means that the ad should use the cached version. 

Is it possible to add a checkbox or something that allows us to ignore the payload of certain scripts that we are certain of are being used by the main site (and therefore cached)? Or just have Gardr ignore certain scripts when validating?

**Comment by sveisvei** [comment]
This must be a bug on this right now, will get time soon to work on validator again. https://github.com/gardr/validator/issues/33

**Comment by wwalmnes** [comment]
Ok. Thanks for the information :)

**Comment by sveisvei** [comment]
jquery bug should be fixed now, but I can see you guys host a older version of jquery when I run against the validator now.

```
jquery: {
        versionsBack: 3
}
```

as option will allow older versions.
