### ISSUE TITLE
Box-sizing styling issue: Styling from style-tag without class or ID prefix found

### ISSUE THREAD

**Issue by wwalmnes** [gardr/validator-web#58]
I prefer to set my box-sizing to border-box and I do so like this (taken from here: http://www.paulirish.com/2012/box-sizing-border-box-ftw/):
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
However, this conflicts with the Gardr validation as I should not style without a class or ID prefix (and I agree with this in most cases).
![screen shot 2015-02-27 at 12 17 21](https://cloud.githubusercontent.com/assets/1506750/6411905/97b678a8-be7d-11e4-8560-c9a67c75ee00.png)

Should this never be done ? Is it possible to have some exceptions to to the rule? Perhaps users can add an "ignore marker"? Although this could defeat the purpose of the validator because someone might be tempted to ignore the whole stylesheet :p.

**Comment by sveisvei** [comment]
I think the _ideal_ is to create banner-ads as `components`, and you therefor package your markup and styles non-conflicting and self providing. The iframe as a container and the html as root might not always be available in the future, e.g. if a Shadow DOM is the container instead of an Iframe.

**Comment by wwalmnes** [comment]
Sorry for the late response. 

You are absolutely correct! I must have been out of my mind.
